name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linting
        run: pnpm lint

      - name: Validate content
        run: pnpm validate:content

      - name: Generate Prisma Client
        run: pnpm prisma:generate

      - name: Build application
        run: pnpm build

      - name: Upload build artifacts
        if: \${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next/
          retention-days: 7
